host: https://testrailtestdata.testrail.io/
project: TestNG
username: aveer.ceejay@findours.com
key: dKnFrognrQWvNKPZ/rbU-XW.Gu1/RpjMT7FjxOaUM
title: LoginTest_03.xml
run_id: 3
suite_id: 3
file: C:\Users\Hasan Abdullah\IdeaProjects\BachelorArbeitNeu\report_sample\TEST-TestSuite.xml
